---
title: "Gadget model output"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
params: 
  fit: fit
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.width=12.5,
  fig.height=5,
  # collapse = TRUE,
  message = FALSE,
  warning = FALSE
)
```

Annual plot
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Catches

```{r}
plotly::ggplotly(plot_catch(fit)) %>% 
  plotly::layout(legend=list(x=0, y = 1, 
                             xanchor='left',
                             yanchor='bottom',
                             orientation='h'))
```

### Harvest rate

```{r}
plotly::ggplotly(plot_hr(fit) + ggplot2::theme(legend.position = "none"))
```


Column {data-width=500}
-----------------------------------------------------------------------

### Recruitment

```{r}
plotly::ggplotly(plot_rec(fit) + ggplot2::theme(legend.position = "none"))
```

### Biomass

```{r}
plotly::ggplotly(
  plot_biomass(fit, total = TRUE) + ggplot2::theme(legend.position = "none"))
```

Catches
=======================================================================

Row
-----------------------------------------------------------------------

### Catches

```{r, fig.height = 5, fig.width = 6.25}
plot_catch(fit, type = "fleet", base_size = 12) +
  ggplot2::guides(fill=ggplot2::guide_legend(nrow=2,byrow=TRUE)) +
  ggplot2::theme(legend.position = "bottom")

# plotly::subplot(plot_catch(fit, type = "fleet"),
#                 plot_catch(fit, type = "hr"),
#                 margin = 0.05,
#                 titleX = TRUE,
#                 titleY = TRUE) # %>% 
# plotly::layout(legend=list(x=0, y = 1, 
#                            xanchor='left',
#                            yanchor='bottom',
#                            orientation='h')) 

```

Row
-----------------------------------------------------------------------

### Harvest rate

```{r, fig.height = 5, fig.width = 6.25}
plot_catch(fit, type = "hr", base_size = 12) +
  ggplot2::guides(fill=ggplot2::guide_legend(nrow=2,byrow=TRUE)) +
  ggplot2::theme(legend.position = "bottom")
```


Survey indices
=======================================================================

```{r}
plotly::ggplotly(plot_si(fit))
```


Catch distributions 
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

```{r, echo = FALSE}
x <- plot_catchdist(fit)
```

```{r, echo = FALSE, results='asis'}

for(i in seq_along(x)) {
  
  cat("  \n###",  names(x)[i], "  \n")
  print(x[[i]])
  cat("  \n")
}

```

Stock distribution 
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

```{r, echo = FALSE}
if (!is.null(fit$stockdist)) 
  x <- plot_stockdist(fit, type = "model_fit", stocks = "separate") 
```

```{r, echo = FALSE, results='asis'}
if (!is.null(fit$stockdist)){ 
  for(i in seq_along(x)) {
    
    cat("  \n###",  names(x)[i], "  \n")
    print(x[[i]])
    cat("  \n")
  }
} else {
  cat('No stock distribution data')
}
```

### Stock composition

```{r, echo = FALSE}
if (!is.null(fit$stockdist)){ 
  plot_stockdist(fit, type = "stock_composition") 
}else{
  cat('No stock distribution data')
}
```

### Length distribution

```{r, echo = FALSE}
if (!is.null(fit$stock.full)){ 
  plot_ldist(fit, ggridges = TRUE) 
}else{
  cat('No data')
}
```

Suitability
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

```{r, echo = FALSE}
x <- plot_suitability(fit, fleets = NULL)
```

```{r, echo = FALSE, results='asis'}

for(i in seq_along(x)) {
  
  cat("  \n###",  names(x)[i], "  \n")
  print(x[[i]] + 
          ggplot2::theme(legend.position = "top")
  )
  cat("  \n")
}

```

Age
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

```{r, echo = FALSE}
x <- plot_agelength(fit)
# x <- lapply(x, function(k) plotly::ggplotly(k))
```

```{r, echo = FALSE, results='asis'}

for(i in seq_along(x)) {
  
  cat("  \n###",  names(x)[i], "  \n")
  print(x[[i]])
  cat("  \n")
}
```

### Growth

```{r}
plot_growth(fit) + ggplot2::theme(legend.position = "none")
```

### Age composition

```{r}
plotly::ggplotly(plot_agecomp(fit, type = "bubble")) %>% plotly::hide_legend()
```

Residuals & likelihood
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

### Residuals

```{r,fig.height = 5, fig.width = 12.5}
plot_resid(fit)
```

### Raw likelihood

```{r, fig.height = 5, fig.width = 12.5}
plot_likelihood(fit)
```

### Weighted likelihood

```{r, fig.height = 5, fig.width = 12.5}
plot_likelihood(fit, type = "weighted")
```

### Total

```{r}
plot_likelihood(fit, type = "total")
```

Parameters
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

### Relative to boundaries

```{r}
plotly::ggplotly(plot_param(fit))
```

### Weights

```{r}
plot_weight(fit, log_scale = TRUE)
```

### Growth parameters & Z

```{r}
DT::datatable(fit$params %>% 
                dplyr::filter(grepl("K$|Linf|recl$|M$|rec.sd|init.F", .data$switch)) %>% 
                dplyr::arrange(switch),
              options = list(pageLength = 500)) %>%
  DT::formatRound(columns=c('value'), digits=3)
```

### All parameters 

```{r}
DT::datatable(fit$params, options = list(pageLength = 500)) %>%
  DT::formatRound(columns=c('value'), digits=3)
```
